databases:
  - name: altos-fontibon-db

services:
  - type: web
    name: proyecto_altos_de_fontibon
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn app.app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.app.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: altos-fontibon-db
          property: connectionString