services:
  - type: web
    name: proyecto_altos_de_fontibon
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.app.settings
      - key: PYTHON_VERSION
        value: 3.11
